apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
  creationTimestamp: '2019-10-29T06:38:07Z'
  generation: 1
  labels:
    app: ab-test
  name: ab-test
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ab-test
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ab-test
    spec:
      containers:
        - args:
            - run.py
            - stragegy_grpc_server.py
          command:
            - python
          env:
            - name: LANG
              value: C.UTF-8
            - name: GPG_KEY
              value: 0D96DF4D4110E5C43FBFB17F2D347EA6AA65421D
            - name: PYTHON_GET_PIP_URL
              value: >-
                https://github.com/pypa/get-pip/raw/309a56c5fd94bd1134053a541cb4657a4e47e09d/get-pip.py
            - name: PYTHON_GET_PIP_SHA256
              value: 57e3643ff19f018f8a00dfaa6b7e4620e3c1a7a2171fd218425366ec006b3bfe
          image: 'registry-vpc.cn-beijing.aliyuncs.com/beijing-mirror/ab-test:1.0.3'
          imagePullPolicy: IfNotPresent
          name: ab-test
          ports:
            - containerPort: 50051
              hostPort: 5201
              name: http
              protocol: TCP
            - containerPort: 5200
              hostPort: 50052
              name: grpc
              protocol: TCP
          resources:
            requests:
              cpu: 250m
              memory: 512Mi


