# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stragegy.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='stragegy.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0estragegy.proto\"/\n\x0bGetStragegy\x12\x0f\n\x07test_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\tb\x06proto3')
)




_GETSTRAGEGY = _descriptor.Descriptor(
  name='GetStragegy',
  full_name='GetStragegy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='test_id', full_name='GetStragegy.test_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='GetStragegy.user_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=65,
)

DESCRIPTOR.message_types_by_name['GetStragegy'] = _GETSTRAGEGY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetStragegy = _reflection.GeneratedProtocolMessageType('GetStragegy', (_message.Message,), {
  'DESCRIPTOR' : _GETSTRAGEGY,
  '__module__' : 'stragegy_pb2'
  # @@protoc_insertion_point(class_scope:GetStragegy)
  })
_sym_db.RegisterMessage(GetStragegy)


# @@protoc_insertion_point(module_scope)
